; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-unroll -mtriple=v850 -S %s | FileCheck %s

; V850 loop unrolling preferences:
; - Small loops (cost < 12) are force-unrolled when trip count is known
; - Loops in optsize functions are not unrolled
; - Loops with calls to external functions are not unrolled

; Small known trip count: fully unrolled because Force=true for cost < 12.
define void @small_known_trip(ptr %p) {
; CHECK-LABEL: @small_known_trip(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    store i32 0, ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[PTR_1:%.*]] = getelementptr i32, ptr [[P]], i32 1
; CHECK-NEXT:    store i32 1, ptr [[PTR_1]], align 4
; CHECK-NEXT:    [[PTR_2:%.*]] = getelementptr i32, ptr [[P]], i32 2
; CHECK-NEXT:    store i32 2, ptr [[PTR_2]], align 4
; CHECK-NEXT:    [[PTR_3:%.*]] = getelementptr i32, ptr [[P]], i32 3
; CHECK-NEXT:    store i32 3, ptr [[PTR_3]], align 4
; CHECK-NEXT:    [[PTR_4:%.*]] = getelementptr i32, ptr [[P]], i32 4
; CHECK-NEXT:    store i32 4, ptr [[PTR_4]], align 4
; CHECK-NEXT:    [[PTR_5:%.*]] = getelementptr i32, ptr [[P]], i32 5
; CHECK-NEXT:    store i32 5, ptr [[PTR_5]], align 4
; CHECK-NEXT:    [[PTR_6:%.*]] = getelementptr i32, ptr [[P]], i32 6
; CHECK-NEXT:    store i32 6, ptr [[PTR_6]], align 4
; CHECK-NEXT:    [[PTR_7:%.*]] = getelementptr i32, ptr [[P]], i32 7
; CHECK-NEXT:    store i32 7, ptr [[PTR_7]], align 4
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %ptr = getelementptr i32, ptr %p, i32 %i
  store i32 %i, ptr %ptr
  %i.next = add nuw nsw i32 %i, 1
  %cmp = icmp ult i32 %i.next, 8
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Same loop with optsize: NOT unrolled (OptSizeThreshold = 0).
define void @small_known_trip_optsize(ptr %p) #0 {
; CHECK-LABEL: @small_known_trip_optsize(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[PTR:%.*]] = getelementptr i32, ptr [[P:%.*]], i32 [[I]]
; CHECK-NEXT:    store i32 [[I]], ptr [[PTR]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i32 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[I_NEXT]], 8
; CHECK-NEXT:    br i1 [[CMP]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %ptr = getelementptr i32, ptr %p, i32 %i
  store i32 %i, ptr %ptr
  %i.next = add nuw nsw i32 %i, 1
  %cmp = icmp ult i32 %i.next, 8
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Loop with external call: NOT unrolled (calls prevent unrolling).
declare void @external(i32)
define void @loop_with_call(i32 %n) {
; CHECK-LABEL: @loop_with_call(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP_ENTRY:%.*]] = icmp sgt i32 [[N:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP_ENTRY]], label [[LOOP_PREHEADER:%.*]], label [[EXIT:%.*]]
; CHECK:       loop.preheader:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ [[I_NEXT:%.*]], [[LOOP]] ], [ 0, [[LOOP_PREHEADER]] ]
; CHECK-NEXT:    call void @external(i32 [[I]])
; CHECK-NEXT:    [[I_NEXT]] = add nuw i32 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %cmp.entry = icmp sgt i32 %n, 0
  br i1 %cmp.entry, label %loop, label %exit

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  call void @external(i32 %i)
  %i.next = add nuw i32 %i, 1
  %cmp = icmp ult i32 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

attributes #0 = { optsize }
