; RUN: llc -mtriple=v850 -mcpu=g4mh -O2 < %s | FileCheck %s

; Test that the 4x-unrolled loop generates 4 addf.s in the main body.
; This IR was generated by clang -O2 with V850 TTI UnrollPreferences
; limiting to MaxCount=4.

; CHECK-LABEL: vec_add:
; Main loop: exactly 4 addf.s operations (4x unroll)
; CHECK:       addf.s
; CHECK:       addf.s
; CHECK:       addf.s
; CHECK:       addf.s
; CHECK:       loop
; Remainder: scalar loop with 1 addf.s
; CHECK:       addf.s
; CHECK:       loop

define void @vec_add(ptr noalias %c, ptr noalias %a, ptr noalias %b, i32 %n) {
entry:
  %cmp = icmp sgt i32 %n, 0
  br i1 %cmp, label %preheader, label %exit

preheader:
  %rem = and i32 %n, 3
  %cmp.ult = icmp ult i32 %n, 4
  br i1 %cmp.ult, label %remainder.check, label %main.preheader

main.preheader:
  %unroll_iter = and i32 %n, -4
  br label %main.loop

main.loop:
  %i = phi i32 [0, %main.preheader], [%i.next, %main.loop]
  ; Iteration 0
  %p.a0 = getelementptr float, ptr %a, i32 %i
  %v.a0 = load float, ptr %p.a0
  %p.b0 = getelementptr float, ptr %b, i32 %i
  %v.b0 = load float, ptr %p.b0
  %r0 = fadd float %v.a0, %v.b0
  %p.c0 = getelementptr float, ptr %c, i32 %i
  store float %r0, ptr %p.c0
  ; Iteration 1
  %i1 = or disjoint i32 %i, 1
  %p.a1 = getelementptr float, ptr %a, i32 %i1
  %v.a1 = load float, ptr %p.a1
  %p.b1 = getelementptr float, ptr %b, i32 %i1
  %v.b1 = load float, ptr %p.b1
  %r1 = fadd float %v.a1, %v.b1
  %p.c1 = getelementptr float, ptr %c, i32 %i1
  store float %r1, ptr %p.c1
  ; Iteration 2
  %i2 = or disjoint i32 %i, 2
  %p.a2 = getelementptr float, ptr %a, i32 %i2
  %v.a2 = load float, ptr %p.a2
  %p.b2 = getelementptr float, ptr %b, i32 %i2
  %v.b2 = load float, ptr %p.b2
  %r2 = fadd float %v.a2, %v.b2
  %p.c2 = getelementptr float, ptr %c, i32 %i2
  store float %r2, ptr %p.c2
  ; Iteration 3
  %i3 = or disjoint i32 %i, 3
  %p.a3 = getelementptr float, ptr %a, i32 %i3
  %v.a3 = load float, ptr %p.a3
  %p.b3 = getelementptr float, ptr %b, i32 %i3
  %v.b3 = load float, ptr %p.b3
  %r3 = fadd float %v.a3, %v.b3
  %p.c3 = getelementptr float, ptr %c, i32 %i3
  store float %r3, ptr %p.c3
  ; Loop control
  %i.next = add i32 %i, 4
  %cmp.main = icmp eq i32 %i.next, %unroll_iter
  br i1 %cmp.main, label %remainder.check, label %main.loop

remainder.check:
  %i.rem = phi i32 [0, %preheader], [%i.next, %main.loop]
  %has.rem = icmp eq i32 %rem, 0
  br i1 %has.rem, label %exit, label %rem.loop

rem.loop:
  %j = phi i32 [%i.rem, %remainder.check], [%j.next, %rem.loop]
  %cnt = phi i32 [0, %remainder.check], [%cnt.next, %rem.loop]
  %p.a.r = getelementptr float, ptr %a, i32 %j
  %v.a.r = load float, ptr %p.a.r
  %p.b.r = getelementptr float, ptr %b, i32 %j
  %v.b.r = load float, ptr %p.b.r
  %r.r = fadd float %v.a.r, %v.b.r
  %p.c.r = getelementptr float, ptr %c, i32 %j
  store float %r.r, ptr %p.c.r
  %j.next = add i32 %j, 1
  %cnt.next = add i32 %cnt, 1
  %cmp.rem = icmp eq i32 %cnt.next, %rem
  br i1 %cmp.rem, label %exit, label %rem.loop

exit:
  ret void
}
